# Generated by Django 5.1.15 on 2026-09-25 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(max_length=20)),
                ('year', models.PositiveSmallIntegerField()),
                ('prefix', models.CharField(max_length=10)),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'verbose_name_plural': 'document series',
                'constraints': [models.UniqueConstraint(fields=('org', 'doc_type', 'year'), name='uniq_doc_series')],
            },
        ),
    ]
