# Generated by Django 5.1.15 on 2026-09-26 09:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_membership_carrier_membership_party'),
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_type', models.CharField(choices=[('pod', 'Proof of delivery'), ('commercial_invoice', 'Commercial invoice'), ('packing_list', 'Packing list'), ('bill_of_lading', 'Bill of lading'), ('air_waybill', 'Air waybill'), ('cmr', 'CMR consignment note'), ('customs', 'Customs declaration'), ('certificate', 'Certificate (origin, phyto, DG)'), ('other', 'Other')], max_length=20)),
                ('file_name', models.CharField(max_length=200)),
                ('content_type', models.CharField(max_length=60)),
                ('size', models.PositiveIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('content', models.BinaryField()),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('visible_to_customer', models.BooleanField(default=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='shipments.shipment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
