# Generated by Django 5.1.15 on 2026-09-26 06:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_membership_carrier_membership_party'),
        ('shipments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentException',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('eta_overdue', 'Past ETA'), ('eta_at_risk', 'ETA at risk'), ('stale_tracking', 'No recent tracking update'), ('customs_dwell', 'Long customs dwell'), ('long_hold', 'On hold too long'), ('delay_reported', 'Delay reported')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='open', max_length=15)),
                ('title', models.CharField(max_length=160)),
                ('detail', models.CharField(blank=True, max_length=500)),
                ('detected_at', models.DateTimeField()),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.CharField(blank=True, max_length=500)),
                ('auto_resolved', models.BooleanField(default=False)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='shipments.shipment')),
            ],
            options={
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['org', 'status', 'severity'], name='exc_org_status_sev')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'resolved'), _negated=True), fields=('shipment', 'kind'), name='uniq_unresolved_exception_per_kind')],
            },
        ),
    ]
