"""Reference data for the demo workspace: real UN/LOCODEs, coordinates and trade lanes."""

# code, name, kind, city, country, lat, lng, timezone
LOCATIONS = [
    ("AEJEA", "Jebel Ali Port", "seaport", "Dubai", "AE", 25.0114, 55.0610, "Asia/Dubai"),
    (
        "AEDXB",
        "Dubai International Airport",
        "airport",
        "Dubai",
        "AE",
        25.2532,
        55.3657,
        "Asia/Dubai",
    ),
    ("AEAUH", "Khalifa Port", "seaport", "Abu Dhabi", "AE", 24.8090, 54.6450, "Asia/Dubai"),
    (
        "JAFZADC",
        "Gulfstream DC, JAFZA South",
        "warehouse",
        "Dubai",
        "AE",
        24.9857,
        55.0917,
        "Asia/Dubai",
    ),
    ("OMSOH", "Sohar Port & Freezone", "seaport", "Sohar", "OM", 24.5000, 56.6200, "Asia/Muscat"),
    ("SAJED", "Jeddah Islamic Port", "seaport", "Jeddah", "SA", 21.4700, 39.1700, "Asia/Riyadh"),
    ("SARUH", "Riyadh Dry Port", "inland", "Riyadh", "SA", 24.6800, 46.7800, "Asia/Riyadh"),
    (
        "INNSA",
        "Nhava Sheva (JNPT)",
        "seaport",
        "Navi Mumbai",
        "IN",
        18.9500,
        72.9500,
        "Asia/Kolkata",
    ),
    (
        "INBOM",
        "Mumbai CSM International Airport",
        "airport",
        "Mumbai",
        "IN",
        19.0896,
        72.8656,
        "Asia/Kolkata",
    ),
    (
        "CNSHA",
        "Shanghai Yangshan Port",
        "seaport",
        "Shanghai",
        "CN",
        30.6260,
        122.0650,
        "Asia/Shanghai",
    ),
    (
        "CNPVG",
        "Shanghai Pudong Airport",
        "airport",
        "Shanghai",
        "CN",
        31.1443,
        121.8083,
        "Asia/Shanghai",
    ),
    (
        "SGSIN",
        "Port of Singapore",
        "seaport",
        "Singapore",
        "SG",
        1.2644,
        103.8220,
        "Asia/Singapore",
    ),
    (
        "NLRTM",
        "Port of Rotterdam",
        "seaport",
        "Rotterdam",
        "NL",
        51.9500,
        4.1400,
        "Europe/Amsterdam",
    ),
    (
        "NLAMS",
        "Amsterdam Schiphol Airport",
        "airport",
        "Amsterdam",
        "NL",
        52.3105,
        4.7683,
        "Europe/Amsterdam",
    ),
    ("DEHAM", "Port of Hamburg", "seaport", "Hamburg", "DE", 53.5400, 9.9700, "Europe/Berlin"),
    (
        "GBLHR",
        "London Heathrow Airport",
        "airport",
        "London",
        "GB",
        51.4700,
        -0.4543,
        "Europe/London",
    ),
    (
        "USNYC",
        "Port of New York & New Jersey",
        "seaport",
        "Newark",
        "US",
        40.6840,
        -74.1450,
        "America/New_York",
    ),
    (
        "SESTO",
        "Nordic Home DC, Stockholm",
        "warehouse",
        "Stockholm",
        "SE",
        59.3293,
        18.0686,
        "Europe/Stockholm",
    ),
]

# name, code, mode, country
CARRIERS = [
    ("Maersk Line", "MAEU", "ocean", "DK"),
    ("MSC Mediterranean Shipping", "MSCU", "ocean", "CH"),
    ("Hapag-Lloyd", "HLCU", "ocean", "DE"),
    ("Emirates SkyCargo", "EK", "air", "AE"),
    ("Qatar Airways Cargo", "QR", "air", "QA"),
    ("Desert Line Transport", "DLT", "road", "AE"),
    ("Gulf Hauliers", "GHL", "road", "AE"),
]

# carrier code → [(plate, type, capacity_kg)]
VEHICLES = {
    "DLT": [
        ("DXB-P-48213", "tractor_trailer", 26000),
        ("DXB-P-48214", "tractor_trailer", 26000),
        ("DXB-K-10977", "reefer", 20000),
        ("DXB-J-55102", "box_truck", 8000),
    ],
    "GHL": [
        ("SHJ-3-77120", "tractor_trailer", 25000),
        ("SHJ-3-77121", "flatbed", 24000),
        ("AUH-5-30418", "van", 1500),
    ],
}

# carrier code → [(name, phone, license)]
DRIVERS = {
    "DLT": [
        ("Imran Qureshi", "+971 50 412 7781", "DXB-HV-2291045"),
        ("Joseph Mathew", "+971 55 208 1934", "DXB-HV-1874412"),
        ("Bilal Siddiqui", "+971 52 671 0452", "DXB-HV-3019273"),
    ],
    "GHL": [
        ("Sunil Perera", "+971 50 993 4120", "SHJ-HV-7712048"),
        ("Tariq Al Amiri", "+971 56 311 8805", "AUH-HV-4401157"),
    ],
}

# name, code, customer?, shipper?, consignee?, city, country, contact, email
PARTIES = [
    (
        "Nordic Home Retail AB",
        "NORDIC",
        True,
        False,
        True,
        "Stockholm",
        "SE",
        "Elena Kovacs",
        "logistics@nordichome.example",
    ),
    (
        "Al Noor Electronics LLC",
        "ALNOOR",
        True,
        True,
        True,
        "Dubai",
        "AE",
        "Faisal Karim",
        "imports@alnoor.example",
    ),
    (
        "Emirates Agro Foods",
        "EAGRO",
        True,
        True,
        True,
        "Dubai",
        "AE",
        "Mariam Saeed",
        "supply@eagro.example",
    ),
    (
        "Bharat Auto Components",
        "BHARAT",
        True,
        True,
        False,
        "Pune",
        "IN",
        "Vikram Joshi",
        "exports@bharatauto.example",
    ),
    (
        "Ningbo Homeware Manufacturing",
        "NINGBO",
        False,
        True,
        False,
        "Ningbo",
        "CN",
        "Wei Zhang",
        "sales@ningbohome.example",
    ),
    (
        "Shenzhen Brightlight Electronics",
        "BRIGHT",
        False,
        True,
        False,
        "Shenzhen",
        "CN",
        "Lily Huang",
        "export@brightlight.example",
    ),
    (
        "Kerala Spice Exports",
        "KSPICE",
        False,
        True,
        False,
        "Kochi",
        "IN",
        "Anil Nair",
        "ops@keralaspice.example",
    ),
    (
        "Hamburg Maschinenbau GmbH",
        "HMBAU",
        False,
        True,
        False,
        "Hamburg",
        "DE",
        "Jonas Weber",
        "versand@hmbau.example",
    ),
    (
        "Riyadh Retail Hub",
        "RRHUB",
        False,
        False,
        True,
        "Riyadh",
        "SA",
        "Khalid Otaibi",
        "receiving@rrhub.example",
    ),
    (
        "Muscat Trading LLC",
        "MUSCAT",
        False,
        False,
        True,
        "Muscat",
        "OM",
        "Salim Al Harthy",
        "stores@muscattrading.example",
    ),
    (
        "Rotterdam Fresh Imports BV",
        "RFRESH",
        False,
        False,
        True,
        "Rotterdam",
        "NL",
        "Eva de Vries",
        "inbound@rfresh.example",
    ),
    (
        "East Coast Auto Parts Inc",
        "ECAP",
        False,
        False,
        True,
        "Newark",
        "US",
        "Mike Russo",
        "receiving@ecap.example",
    ),
]

# Parties in a customer's private address book: (name, code, owner code, city, country)
ADDRESS_BOOK = [
    ("Nordic Home DC Stockholm", "NHDCSTO", "NORDIC", "Stockholm", "SE"),
    ("Nordic Home Store Oslo", "NHOSLO", "NORDIC", "Oslo", "NO"),
]

# Trade lanes: origin, destination, mode, service, carrier, transit days,
#              customer, shipper, consignee, commodity, hs code, incoterm
LANES = [
    (
        "CNSHA",
        "NLRTM",
        "ocean",
        "fcl",
        "MSCU",
        32,
        "NORDIC",
        "NINGBO",
        "NHDCSTO",
        "Flat-pack furniture",
        "940360",
        "FOB",
    ),
    (
        "CNSHA",
        "AEJEA",
        "ocean",
        "fcl",
        "MAEU",
        22,
        "ALNOOR",
        "BRIGHT",
        "ALNOOR",
        "LED televisions",
        "852872",
        "CIF",
    ),
    (
        "INNSA",
        "AEJEA",
        "ocean",
        "lcl",
        "HLCU",
        6,
        "EAGRO",
        "KSPICE",
        "EAGRO",
        "Whole black pepper",
        "090411",
        "CFR",
    ),
    (
        "AEJEA",
        "NLRTM",
        "ocean",
        "fcl",
        "MAEU",
        21,
        "NORDIC",
        "NINGBO",
        "NHDCSTO",
        "Ceramic tableware",
        "691200",
        "FOB",
    ),
    (
        "DEHAM",
        "AEJEA",
        "ocean",
        "fcl",
        "HLCU",
        24,
        "BHARAT",
        "HMBAU",
        "ALNOOR",
        "CNC machining centres",
        "845710",
        "DAP",
    ),
    (
        "SGSIN",
        "AEJEA",
        "ocean",
        "lcl",
        "MSCU",
        12,
        "ALNOOR",
        "BRIGHT",
        "ALNOOR",
        "Smartphone accessories",
        "851762",
        "FOB",
    ),
    (
        "INNSA",
        "USNYC",
        "ocean",
        "fcl",
        "MSCU",
        30,
        "BHARAT",
        "BHARAT",
        "ECAP",
        "Brake assemblies",
        "870830",
        "CIF",
    ),
    (
        "CNPVG",
        "AEDXB",
        "air",
        "air_exp",
        "EK",
        1,
        "ALNOOR",
        "BRIGHT",
        "ALNOOR",
        "Laptop computers",
        "847130",
        "CPT",
    ),
    (
        "INBOM",
        "AEDXB",
        "air",
        "air_std",
        "EK",
        1,
        "EAGRO",
        "KSPICE",
        "EAGRO",
        "Fresh mangoes (chilled)",
        "080450",
        "CPT",
    ),
    (
        "AEDXB",
        "NLAMS",
        "air",
        "air_std",
        "EK",
        1,
        "NORDIC",
        "NINGBO",
        "NHDCSTO",
        "Designer lamps",
        "940540",
        "FCA",
    ),
    (
        "CNPVG",
        "NLAMS",
        "air",
        "air_exp",
        "QR",
        2,
        "NORDIC",
        "NINGBO",
        "NHDCSTO",
        "Textile samples",
        "630493",
        "EXW",
    ),
    (
        "AEDXB",
        "GBLHR",
        "air",
        "air_std",
        "QR",
        1,
        "EAGRO",
        "EAGRO",
        "RFRESH",
        "Dates (premium)",
        "080410",
        "DAP",
    ),
    (
        "AEJEA",
        "SARUH",
        "road",
        "ftl",
        "DLT",
        3,
        "ALNOOR",
        "ALNOOR",
        "RRHUB",
        "Home appliances",
        "845011",
        "DAP",
    ),
    (
        "JAFZADC",
        "OMSOH",
        "road",
        "ftl",
        "DLT",
        1,
        "EAGRO",
        "EAGRO",
        "MUSCAT",
        "Frozen poultry",
        "020714",
        "DDP",
    ),
    (
        "JAFZADC",
        "SAJED",
        "road",
        "ltl",
        "GHL",
        4,
        "ALNOOR",
        "ALNOOR",
        "RRHUB",
        "Air conditioners",
        "841510",
        "DAP",
    ),
    (
        "AEJEA",
        "AEAUH",
        "road",
        "ltl",
        "GHL",
        1,
        "BHARAT",
        "BHARAT",
        "ALNOOR",
        "Automotive filters",
        "842123",
        "DDP",
    ),
]

CONTAINER_OWNER = {"MAEU": "MSKU", "MSCU": "MSCU", "HLCU": "HLXU"}
