# Generated by Django 5.1.15 on 2026-09-26 09:19

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterdata', '0001_initial'),
        ('organizations', '0002_membership_carrier_membership_party'),
        ('shipments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(1)])),
                ('currency', models.CharField(max_length=3)),
                ('transit_hours', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('withdrawn', 'Withdrawn'), ('won', 'Won'), ('lost', 'Not selected')], default='submitted', max_length=10)),
                ('revision', models.PositiveSmallIntegerField(default=1)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='masterdata.carrier')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['amount'],
            },
        ),
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(editable=False, max_length=30)),
                ('status', models.CharField(choices=[('open', 'Open for bids'), ('closed', 'Closed · awaiting award'), ('awarded', 'Awarded'), ('cancelled', 'Cancelled')], default='open', max_length=10)),
                ('vehicle_type', models.CharField(choices=[('tractor_trailer', 'Tractor + trailer'), ('box_truck', 'Box truck'), ('reefer', 'Reefer'), ('flatbed', 'Flatbed'), ('van', 'Van')], max_length=20)),
                ('pickup_at', models.DateTimeField()),
                ('deliver_by', models.DateTimeField()),
                ('closes_at', models.DateTimeField(help_text='Bidding deadline')),
                ('target_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Internal budget; never shown to carriers', max_digits=12, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('notes', models.TextField(blank=True, help_text='Shown to invited carriers')),
                ('cancel_reason', models.CharField(blank=True, max_length=255)),
                ('awarded_bid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenders.bid')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('invited_carriers', models.ManyToManyField(related_name='tender_invitations', to='masterdata.carrier')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenders', to='shipments.shipment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='bid',
            name='tender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='tenders.tender'),
        ),
        migrations.AddIndex(
            model_name='tender',
            index=models.Index(fields=['org', 'status', 'closes_at'], name='tnd_org_status_closes'),
        ),
        migrations.AddConstraint(
            model_name='tender',
            constraint=models.UniqueConstraint(fields=('org', 'reference'), name='uniq_tender_reference'),
        ),
        migrations.AddConstraint(
            model_name='tender',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['open', 'closed', 'awarded'])), fields=('shipment',), name='uniq_live_tender_per_shipment'),
        ),
        migrations.AddConstraint(
            model_name='bid',
            constraint=models.UniqueConstraint(fields=('tender', 'carrier'), name='uniq_bid_per_carrier'),
        ),
    ]
