# Generated by Django 5.1.15 on 2026-09-25 18:13

import apps.shipments.models
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterdata', '0001_initial'),
        ('organizations', '0002_membership_carrier_membership_party'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(editable=False, max_length=30)),
                ('tracking_number', models.CharField(default=apps.shipments.models.new_tracking_number, editable=False, max_length=12, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('booked', 'Booked'), ('picked_up', 'Picked up'), ('in_transit', 'In transit'), ('at_customs', 'At customs'), ('out_for_delivery', 'Out for delivery'), ('delivered', 'Delivered'), ('on_hold', 'On hold'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('held_from_status', models.CharField(blank=True, editable=False, max_length=20)),
                ('mode', models.CharField(choices=[('air', 'Air'), ('ocean', 'Ocean'), ('road', 'Road')], max_length=10)),
                ('service_type', models.CharField(choices=[('fcl', 'FCL (full container)'), ('lcl', 'LCL (consolidated)'), ('air_std', 'Air standard'), ('air_exp', 'Air express'), ('ftl', 'FTL (full truckload)'), ('ltl', 'LTL (part load)')], max_length=10)),
                ('incoterm', models.CharField(choices=[('EXW', 'EXW · Ex Works'), ('FCA', 'FCA · Free Carrier'), ('FOB', 'FOB · Free On Board'), ('CFR', 'CFR · Cost and Freight'), ('CIF', 'CIF · Cost, Insurance and Freight'), ('CPT', 'CPT · Carriage Paid To'), ('DAP', 'DAP · Delivered At Place'), ('DDP', 'DDP · Delivered Duty Paid')], default='FOB', max_length=3)),
                ('etd', models.DateTimeField(blank=True, null=True, verbose_name='Estimated departure')),
                ('eta', models.DateTimeField(blank=True, null=True, verbose_name='Estimated arrival')),
                ('atd', models.DateTimeField(blank=True, null=True, verbose_name='Actual departure')),
                ('ata', models.DateTimeField(blank=True, null=True, verbose_name='Actual arrival / delivery')),
                ('house_bill', models.CharField(blank=True, help_text='HBL / HAWB number', max_length=40)),
                ('master_bill', models.CharField(blank=True, help_text='MBL / MAWB number', max_length=40)),
                ('voyage_number', models.CharField(blank=True, help_text='Vessel voyage / flight', max_length=40)),
                ('customer_reference', models.CharField(blank=True, help_text='PO / order ref', max_length=60)),
                ('commodity', models.CharField(max_length=150)),
                ('hs_code', models.CharField(blank=True, max_length=12)),
                ('declared_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('is_hazardous', models.BooleanField(default=False)),
                ('is_temperature_controlled', models.BooleanField(default=False)),
                ('special_instructions', models.TextField(blank=True)),
                ('total_packages', models.PositiveIntegerField(default=0)),
                ('gross_weight_kg', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('volume_cbm', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=10)),
                ('chargeable_weight_kg', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='masterdata.carrier')),
                ('consignee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments_received', to='masterdata.party')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments_billed', to='masterdata.party')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments_in', to='masterdata.location')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments_out', to='masterdata.location')),
                ('shipper', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments_sent', to='masterdata.party')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('container', 'Container'), ('pallet', 'Pallet'), ('carton', 'Carton'), ('crate', 'Crate'), ('drum', 'Drum'), ('piece', 'Loose piece')], max_length=10)),
                ('container_type', models.CharField(blank=True, choices=[('20GP', "20' General purpose"), ('40GP', "40' General purpose"), ('40HC', "40' High cube"), ('45HC', "45' High cube"), ('20RF', "20' Reefer"), ('40RF', "40' Reefer")], max_length=4)),
                ('container_number', models.CharField(blank=True, max_length=11)),
                ('seal_number', models.CharField(blank=True, max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('description', models.CharField(blank=True, max_length=150)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Gross weight (kg, line total)')),
                ('length_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True)),
                ('width_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True)),
                ('volume_cbm', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=10)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='shipments.shipment')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TrackingEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(choices=[('BKD', 'Booking confirmed'), ('PUP', 'Cargo picked up'), ('GIN', 'Gate in at origin'), ('LOD', 'Loaded on vessel / aircraft / truck'), ('DEP', 'Departed origin'), ('ARR', 'Arrived at destination hub'), ('DIS', 'Discharged / unloaded'), ('CUS', 'Customs inspection'), ('CLR', 'Customs cleared'), ('OFD', 'Out for delivery'), ('DLV', 'Delivered (POD)'), ('HLD', 'Shipment on hold'), ('RES', 'Hold released'), ('CAN', 'Shipment cancelled'), ('DLY', 'Delay reported'), ('NTE', 'Update')], max_length=3)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('occurred_at', models.DateTimeField()),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('system', 'System'), ('import', 'Bulk import'), ('carrier', 'Carrier'), ('gps', 'GPS')], default='manual', max_length=10)),
                ('is_public', models.BooleanField(default=True, help_text='Visible to the customer and on the public tracking page')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='masterdata.location')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='shipments.shipment')),
            ],
            options={
                'ordering': ['-occurred_at', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['org', 'status', '-created_at'], name='shp_org_status_created'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['org', 'customer', '-created_at'], name='shp_org_customer_created'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['org', 'eta'], name='shp_org_eta'),
        ),
        migrations.AddConstraint(
            model_name='shipment',
            constraint=models.UniqueConstraint(fields=('org', 'reference'), name='uniq_shipment_reference'),
        ),
        migrations.AddConstraint(
            model_name='shipment',
            constraint=models.CheckConstraint(condition=models.Q(('origin', models.F('destination')), _negated=True), name='shipment_origin_ne_destination'),
        ),
        migrations.AddIndex(
            model_name='trackingevent',
            index=models.Index(fields=['shipment', '-occurred_at'], name='evt_shipment_occurred'),
        ),
        migrations.AddIndex(
            model_name='trackingevent',
            index=models.Index(fields=['org', 'code', '-occurred_at'], name='evt_org_code_occurred'),
        ),
    ]
